### ISSUE TITLE
Getting 404 error

### ISSUE THREAD

**Issue by UchihaSR** [vpj/annotate#1]
![inside_ui](https://user-images.githubusercontent.com/52357560/63653709-0f732a80-c78e-11e9-8358-4fae2c6188e2.png)
after this i executed ann.py which output following lines:
**python ann.py **
ui
/home/itachi/annotate/server
WARNING:tornado.access:404 GET /static/index.html (::1) 4.06ms
WARNING:tornado.access:404 GET /static/index.html (::1) 3.29ms
WARNING:tornado.access:404 GET /static/index.html (::1) 2.61ms
when i copy pasted the url, it is showing 404 error.

**Comment by vpj** [comment]
Looks like `__file__` gives a relative path when executed the same location.

I just pushed a fix, please pull and try again.
